" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

syntax on
set number
set relativenumber
set laststatus=2
set mouse=nvc

set autoindent
set tabstop=4
set shiftwidth=4
set noexpandtab

set splitbelow
set splitright

set textwidth=70
set ignorecase

filetype plugin indent on

let g:DoxygenToolkit_authorName="Simon Nagl"
let g:DoxygenToolkit_licenseTag="© 2015 Simon Nagl (see also: LICENSE)"
